import mysql.connector

conn = mysql.connector.connect(host='localhost', user='root', password='cyb101500', database='test', auth_plugin='mysql_native_password')
cursor = conn.cursor()
# cursor.execute('create table customer (id varchar(30) primary key, name varchar(10), age int, gender int )')
# cursor.execute('insert into customer values(%s, %s, %s, %s)', ['TS0000001', 'cus1', 18, 1])
# print(cursor.rowcount)
# conn.commit()
# cursor.close()
# cursor = conn.cursor()
# cursor.execute('select * from customer')
# values = cursor.fetchall()
# print(values)
# cursor.close()
# conn.close()

# cursor.execute('create table compute (id varchar(20) primary key, name varchar (20), cid varchar(30), constraint compute_to_cid foreign key(cid) references customer(id))')
# cursor.execute('insert into compute values(%s, %s, %s)', ['compute0001', '华硕', 'TS0000001'])
# cursor.execute('insert into compute values(%s, %s, %s)', ['compute0002', '联想', 'TS0000001'])
# cursor.execute('insert into compute values(%s, %s, %s)', ['compute0003', '戴尔', 'TS0000001'])
# print(cursor.rowcount)
# conn.commit()
# cursor.close()
# cursor = conn.cursor()
# cursor.execute('select * from compute')
# print(cursor.fetchall())
# cursor.close()
# conn.close()

# cursor.execute('insert into compute values(%s, %s, %s)', ['compute0001', '华硕', 'TS0000003'])
# conn.commit()
# cursor.close()
# conn.close()